import { defineType, defineField } from "sanity";

export default defineType({
  name: "project",
  title: "Project",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Title", type: "string", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      readOnly: ({ value }) => !!value?.current,
      validation: (r) => r.required(),
    }),
    defineField({ name: "category", title: "Category", type: "string" }),
    defineField({
      name: "priority",
      title: "Priority",
      description: "Controls display order on the homepage and /projects listing. Featured projects appear first.",
      type: "string",
      options: {
        list: [
          { title: "Featured", value: "featured" },
          { title: "High", value: "high" },
          { title: "Normal", value: "normal" },
          { title: "Low", value: "low" },
        ],
        layout: "radio",
      },
      initialValue: "normal",
      validation: (r) => r.required(),
    }),
    defineField({ name: "description", title: "Description", type: "text", rows: 3 }),
    defineField({
      name: "tech",
      title: "Tech Stack",
      type: "array",
      of: [{ type: "string" }],
      validation: (r) =>
        r.custom((items?: string[]) =>
          items && items.some((i) => !i || !i.trim()) ? "Tech entries cannot be empty" : true
        ),
    }),
    defineField({
      name: "image",
      title: "Card Image",
      description: "Shown on the /projects listing card.",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image",
      description: "Full-bleed hero on the project detail page. Falls back to Card Image if empty.",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({ name: "year", title: "Year", type: "string" }),
    defineField({ name: "tagline", title: "Tagline", type: "string" }),
    defineField({ name: "platform", title: "Platform", type: "string" }),
    defineField({ name: "duration", title: "Duration", type: "string" }),
    defineField({ name: "teamSize", title: "Team Size", type: "string" }),
    defineField({ name: "status", title: "Status", type: "string", options: { list: ["Live", "In Progress", "Completed"] } }),
    defineField({
      name: "websiteUrl",
      title: "Website URL",
      description: "Shown as a 'Visit Website' button on the detail page. Only used when Gallery Layout is Desktop. Leave empty to hide.",
      type: "url",
      hidden: ({ parent }) => parent?.galleryType !== "desktop",
      validation: (r) => r.uri({ scheme: ["http", "https"] }),
    }),
    defineField({
      name: "appStoreUrl",
      title: "App Store URL",
      description: "Shown as an 'App Store' button on the detail page. Only used when Gallery Layout is Mobile. Leave empty to hide.",
      type: "url",
      hidden: ({ parent }) => parent?.galleryType !== "mobile",
      validation: (r) => r.uri({ scheme: ["http", "https"] }),
    }),
    defineField({
      name: "playStoreUrl",
      title: "Google Play URL",
      description: "Shown as a 'Google Play' button on the detail page. Only used when Gallery Layout is Mobile. Leave empty to hide.",
      type: "url",
      hidden: ({ parent }) => parent?.galleryType !== "mobile",
      validation: (r) => r.uri({ scheme: ["http", "https"] }),
    }),
    defineField({ name: "challenge", title: "Challenge", type: "text", rows: 5 }),
    defineField({ name: "solution", title: "Solution", type: "text", rows: 5 }),
    defineField({ name: "client", title: "Client Info", type: "clientInfo" }),
    defineField({ name: "features", title: "Features", type: "array", of: [{ type: "projectFeature" }] }),
    defineField({
      name: "galleryType",
      title: "Gallery Layout",
      description: "How the screenshots in the Gallery section are framed: phone-shaped for mobile apps, wide for desktop/web apps.",
      type: "string",
      options: {
        list: [
          { title: "Mobile", value: "mobile" },
          { title: "Desktop", value: "desktop" },
        ],
        layout: "radio",
      },
      initialValue: "mobile",
      validation: (r) => r.required(),
    }),
    defineField({ name: "gallery", title: "Gallery", type: "array", of: [{ type: "image", options: { hotspot: true } }] }),
    defineField({ name: "testimonial", title: "Testimonial", type: "projectTestimonial" }),
  ],
  preview: {
    select: { title: "title", subtitle: "category", media: "image" },
  },
});
